volumes:
  postgres-data:
  directus-uploads:
  directus-extensions:
  redis-data:

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

  redis:
    image: redis:7.4-alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped

  directus:
    image: directus/directus:11.17.4
    ports:
      - "${PORT:-8055}:8055"
    env_file:
      - .env
    volumes:
      - directus-uploads:/directus/uploads
      - directus-extensions:/directus/extensions
      - ./mail_templates:/directus/mail_templates
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
